// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    // 1. مقدمه
    'intro',
    
    // 2. متغیرها و ثابت‌ها
    {
      type: 'category',
      label: 'متغیرها و ثابت‌ها',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'variables'}],
    },
    
    // 3. ساختارهای داده
    {
      type: 'category',
      label: 'ساختارهای داده',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'data-structures'}],
    },

    // 4. توابع و متدها
    {
      type: 'category',
      label: 'توابع و متدها',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'functions'}],
    },

    // 5. برنامه‌نویسی شی‌گرا (OOP)
    {
      type: 'category',
      label: 'برنامه‌نویسی شی‌گرا (OOP)',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'oop'}],
    },

    // 6. مفاهیم پیشرفته
    {
      type: 'category',
      label: 'مفاهیم پیشرفته',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'advanced'}],
    },

    // 7. مبانی برنامه‌نویسی
    {
      type: 'category',
      label: 'مبانی برنامه‌نویسی',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'basics'}],
    },

    // 8. Namespace و کتابخانه‌ها
    {
      type: 'category',
      label: 'Namespace و کتابخانه‌ها',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'namespase'}],
    },

    // 9. Unity مقدماتی
    {
      type: 'category',
      label: 'Unity مقدماتی',
      link: {
        type: 'generated-index',
        description: 'شروع کار با Unity و مفاهیم پایه'
      },
      items: [
        'unity/boot',
        {type: 'autogenerated', dirName: 'unity-basics'}
      ],
    },

    // 10. ابزارها و توابع کمکی
    {
      type: 'category',
      label: 'ابزارها و توابع کمکی',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },

    // 11. الگوها و معماری
    {
      type: 'category',
      label: 'الگوها و معماری',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'patterns'}],
    },

    // 12. کلاس‌های مهم Unity
    {
      type: 'category',
      label: 'کلاس‌های مهم Unity',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'unity-calsses'}],
    },

    // 13. سیستم ورودی
    {
      type: 'category',
      label: 'سیستم ورودی (Input System)',
      link: {
        type: 'generated-index',
        description: 'Input System جدید و Touch در Unity'
      },
      items: [
        'unity/newInputSystem',
        'unity/useInputAction',
        'unity/touch',
        'unity/EnhancedTouch',
        'unity/ctx',
        'unity/ctxInput',
      ],
    },

    // 14. UI و Canvas
    {
      type: 'category',
      label: 'رابط کاربری (UI)',
      link: {
        type: 'generated-index',
        description: 'Canvas، Layout و UI در Unity'
      },
      items: [
        {type: 'autogenerated', dirName: 'unity/canvas'},
        'unity/UI/shader',
        'unity/fullscreen',
        'unity/safeArea',
      ],
    },

    // 15. گرافیک 2D
    {
      type: 'category',
      label: 'گرافیک 2D',
      link: {
        type: 'generated-index',
        description: 'Sprite، Line Renderer و گرافیک دوبعدی'
      },
      items: [
        {type: 'autogenerated', dirName: 'unity/spriteEditor'},
        {type: 'autogenerated', dirName: 'unity/linderRender'},
        'unity/gameObjectSize',
      ],
    },

    // 16. منابع و مطالب تکمیلی
    {
      type: 'category',
      label: 'منابع و مطالب تکمیلی',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'resources'}],
    },
  ],
};

export default sidebars;
